version: 2
jobs:   
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "7d:f7:3d:0f:06:9a:31:dd:dc:55:84:d7:27:f9:65:8c"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t jagscol/hola-docker:$CIRCLE_SHA1 .
      - run: docker push jagscol/hola-docker:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no root@157.230.183.90 "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
